name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem
        chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -i github-ec2.pem ${USER}@${HOST} << 'EOF'   

        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
        \. "$HOME/.nvm/nvm.sh"
        nvm install node
        nvm use node
        sudo yum install -y nginx git

        REPO_URL="https://github.com/mystyyyy/reactPractice.git"
        REPO_DIR="/usr/share/nginx/html"

        if [ -d "$REPO_DIR/.git" ]; then
          cd "$REPO_DIR"
          sudo git pull origin main
        else
          rm -rf $REPO_DIR/*
          git clone "$REPO_URL" "$REPO_DIR"
          cd "$REPO_DIR"
        fi

        cd "$REPO_DIR/reactPractice"
        npm install
        npm run build

        sudo systemctl restart nginx
        EOF
